# this is mysql config
[list]
    [list.default]
        driver_name = "mysql"
        data_source_name = "root:Woshiliuwen@1@tcp(101.43.247.25:16033)/kubei2dou?charset=utf8&parseTime=true&loc=Asia%2FChongqing"
        max_open_conn = 20
        max_idle_conn = 10
        max_conn_life_time = 100